---
- name: Configure remote host
  hosts: targets
  become: yes
  tasks:
    - name: Install nginx and php
      apt:
        name:
          - nginx
          - php-fpm
        state: latest
        update_cache: yes

    - name: Ensure nginx starts on boot
      service:
        name: nginx
        enabled: yes
        state: started
